export function markup(a: { csp: string; nonce: string; app: string; editorCss: string; css: string; worker: string; editorWorker: string }) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${a.csp} data:; font-src ${a.csp}; style-src ${a.csp} 'unsafe-inline'; script-src 'nonce-${a.nonce}' blob:; worker-src blob:; connect-src ${a.csp};">
  <link rel="stylesheet" href="${a.editorCss}"><link rel="stylesheet" href="${a.css}"><title>JSON Workbench</title></head>
  <body data-worker="${a.worker}" data-editor-worker="${a.editorWorker}">
  <header class="topbar"><button id="history-toggle" title="Toggle history" aria-label="Toggle history">☰</button><span class="brand-icon">{ }</span><strong>JSON Workbench</strong><span class="private" id="privacy-badge">● Local</span><span class="spacer"></span><button id="sample">Load example</button><button id="new">New</button><button id="share">Share link</button></header>
  <div class="workspace"><aside id="history" hidden><div class="sidebar-heading"><strong>History</strong><span>Saved on this device</span></div><div class="sync-box"><label class="sync-toggle"><input id="sync-toggle" type="checkbox"> Sync history across devices</label><p id="sync-status" class="sync-status">History stays on this device. Enable to share JSON through VS Code Settings Sync.</p><div class="sync-actions"><button id="sync-refresh">Refresh</button><button id="sync-help">Setup guide</button></div></div><input id="history-search" aria-label="Search history" placeholder="Search history…"><div id="history-list"></div></aside>
  <main><div class="documentbar"><input id="document-name" aria-label="Document name" value="Untitled JSON"><span class="spacer"></span><label><input id="binding" type="checkbox" checked> Auto format</label><button id="single" aria-pressed="false">Single pane</button><button id="diff" aria-pressed="false">Diff</button></div>
  <div id="panes"><section class="pane" id="input-pane" aria-label="Input JSON"><div class="pane-heading"><strong>Input</strong><span id="input-status" role="status">Paste JSON to begin</span></div><div id="input-tabs" class="tabs" role="tablist" aria-label="Input view"></div><div id="input-toolbar" class="toolbar"></div><div id="input-editor" class="editor"></div><div id="input-view" class="data-view" hidden></div></section>
  <div id="splitter" role="separator" tabindex="0" aria-label="Resize JSON panes" aria-orientation="vertical" aria-valuemin="20" aria-valuemax="80" aria-valuenow="50"></div>
  <section class="pane" id="output-pane" aria-label="Output JSON"><div class="pane-heading"><strong>Output</strong><span id="output-status" role="status">Formatted result</span></div><div id="output-tabs" class="tabs" role="tablist" aria-label="Output view"></div><div id="output-toolbar" class="toolbar"></div><div id="output-editor" class="editor"></div><div id="output-view" class="data-view" hidden></div></section></div>
  <div id="diff-editor" class="editor" hidden></div>
  <div id="error" role="alert" hidden></div></main></div>
  <footer><span id="size">0 bytes</span><span class="spacer"></span><label>Indent <select id="indent" aria-label="Indent"><option value="1">1 space</option><option value="2" selected>2 spaces</option><option value="3">3 spaces</option><option value="4">4 spaces</option><option value="tab">Tabs</option></select></label><label>Font <select id="font" aria-label="Font size"><option>12</option><option selected>14</option><option>16</option><option>18</option><option>20</option></select></label><button id="wrap" aria-pressed="true">Wrap</button><label>Theme <select id="theme" aria-label="Theme"><option value="auto">VS Code</option><option value="dark">Dark</option><option value="light">Light</option></select></label><button id="help" title="Keyboard shortcuts">?</button></footer>
  <div id="toast" role="status" hidden></div><script nonce="${a.nonce}" src="${a.app}"></script></body></html>`;
}
